services:
  shop_cards:
    env_file:
    - .env
    build:
      context: ./services/shop_cards
      dockerfile: Dockerfile.shopcards
    container_name: shop_cards
    ports: 
      - "${CARD_SERVICE_PORT}:${CARD_SERVICE_PORT}"
    depends_on: 
      cards-db:
        condition: service_healthy
  users:
    env_file:
    - .env
    build:
      context: ./services/users
      dockerfile: Dockerfile.users
    container_name: users
    ports: 
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on: 
      users-db:
        condition: service_healthy
      redis:
        condition: service_healthy
  orders:
    env_file:
    - .env
    build:
      context: ./services/orders
      dockerfile: Dockerfile.orders
    container_name: orders
    ports: 
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    depends_on: 
      shop_cards:
        condition: service_started
      users:
        condition: service_started
      orders-db:
        condition: service_healthy
  gateway:
    env_file:
    - .env
    build:
      context: ./services/gateway
      dockerfile: Dockerfile.gateway
    container_name: gateway
    ports: 
      - "${REST_PORT}:${REST_PORT}"
    depends_on: 
      orders:
        condition: service_started

  # kafka:
  #   image: confluentinc/cp-kafka:8.1.1
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"   # внешний доступ для клиентов
  #     - "29092:29092" # внутренний доступ между контейнерами
  #   environment:
  #     KAFKA_NODE_ID: 1
  #     KAFKA_LISTENERS: PLAINTEXT://localhost:29092,CONTROLLER://localhost:29093,PLAINTEXT_HOST://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_NUM_PARTITIONS: 1
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     CLUSTER_ID: AkzAKoIeTauyH6SPdYZpUg
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  orders-db:
    env_file:
    - .env
    image: postgres:15
    container_name: orders-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${ORDER_DB_NAME}
    restart: always
    ports:
      - "${ORDER_DB_PORT}:${DB_PORT}"
    volumes:
      - orders_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  cards-db:
    env_file:
    - .env
    image: postgres:15
    container_name: cards-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${CARD_DB_NAME}
    ports:
      - "${CARD_DB_PORT}:${DB_PORT}"
    restart: always
    volumes:
      - cards_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  users-db:
    env_file:
    - .env
    image: postgres:15
    container_name: users-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "${USER_DB_PORT}:${DB_PORT}"
    restart: always
    volumes:
      - users_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    env_file:
    - .env
    image: redis:8
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

volumes:
  orders_pgdata:
  users_pgdata:
  cards_pgdata:
  redisdata: