env: "dev"
dsn: "host=${CARD_DB_HOST} user=${DB_USER} password=${DB_PASS} dbname=${CARD_DB_NAME} port=${DB_PORT} sslmode=disable"
grpc:
  port: "${CARD_SERVICE_PORT}"
  timeout: ${CARD_SERVICE_TIMEOUT}s
