env: "dev"
dsn: "host=${USER_DB_HOST} user=${DB_USER} password=${DB_PASS} dbname=${USER_DB_NAME} port=${DB_PORT} sslmode=disable"
grpc:
  port: "${USER_SERVICE_PORT}"
  timeout: ${USER_SERVICE_TIMEOUT}s
redis:
  addr: ${REDIS_ADDR}
  dbnum: 1
access_token_ttl: ${ACCESS_TOKEN_TTL}s
refresh_token_ttl: ${REFRESH_TOKEN_TTL}s
jwt_secret: ${JWT_SECRET}