env: "dev"
user_service:
  addr: "${USER_DB_NAME}:${USER_SERVICE_PORT}"
  timeout: ${USER_SERVICE_TIMEOUT}
  max_retries: ${USER_SERVICE_MAX_RETRIES}
order_service:
  addr: "${ORDER_DB_NAME}:${ORDER_SERVICE_PORT}"
  timeout: ${ORDER_SERVICE_TIMEOUT}
  max_retries: ${ORDER_SERVICE_MAX_RETRIES}
remna_service:
  addr: "${REMNA_SERVICE_HOST}:${REMNA_SERVICE_PORT}"
  timeout: ${REMNA_SERVICE_TIMEOUT}
  max_retries: ${REMNA_SERVICE_MAX_RETRIES}
rest:
  addr: ":${REST_PORT}"
  request_timeout: ${REST_REQUEST_TIMEOUT}
  idle_timout: ${REST_IDLE_TIOMOUT}
refresh_token_ttl: ${REFRESH_TOKEN_TTL}
jwt_secret: ${JWT_SECRET}
bot_token: ${BOT_TOKEN}